### ISSUE TITLE
Leaves with crops on just have a plain color.

### ISSUE THREAD

**Issue by Ayuma-cell** [ExcessiveAmountsOfZombies/Croptopia#387] opened 2022-05-24 15:53 UTC
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Croptopia version.

2.0.0

### What happened?

I've tried disabling shader and ressource pack but it's still there. Not sure what'd be causing it.
![image](https://user-images.githubusercontent.com/68541335/170079110-3419480e-6e6b-4a99-a7c5-7f19ba0edb97.png)

**Comment by JiroCab** [comment] 2022-05-24 16:13
this looks like a incompatibility with another mod, a mod list would help, likely something that alters rendering or just having a problem with texture overlays

**Comment by Ayuma-cell** [comment] 2022-05-24 18:39
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/8765445/latest.log)

**Comment by Ayuma-cell** [comment] 2022-05-24 18:40
Might be worth mentioning that I experience the same issue with botania crops aswell.

**Comment by ExcessiveAmountsOfZombies** [comment] 2022-05-24 23:09
idk maybe try removing dash loader or cull leaves first. but you'll have to do what i mentioned before. only other thing I can see is quilt but no idea if it would be that

**Comment by ExcessiveAmountsOfZombies** [comment] 2022-05-26 18:43
is there an older version of sodium where the issue isn't present? Not sure if it'd be a recent change in sodium that is causing this or it has always been present, but this is the first time since the mod has been published that an issue with sodium has been brought to my attention

**Comment by Ayuma-cell** [comment] 2022-05-26 18:55
Can't really check this since 0.4.1 is the only version available for 1.18.2

**Comment by ExcessiveAmountsOfZombies** [comment] 2022-05-26 19:18
oh, my bad

**Comment by Alkiasan** [comment] 2022-05-28 01:14
Update on this, having the same issue. Note that using Iris shaders actually fixes the problem, it only happens when shaders are disabled. weird.

**Comment by Alkiasan** [comment] 2022-06-04 03:58
Update: In the context of Quilt Loader, this is fixed with the latest ver of QSL

**Closed** 2022-06-04 04:06 UTC
Labels: bug
