### ISSUE TITLE
Recipe errors and some questions.

### ISSUE THREAD

**Issue by wasdspace** [ExcessiveAmountsOfZombies/Croptopia#374] opened 2022-05-05 16:41 UTC
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.0.1

### What happened?

The recipes of **Buttered Green Beans** and **Melon Juice** use wrong tags.

And there may be some bugs(or just my mistakes):
**Beef Jerky** and **Pork Jerky** have no recipes? Or how can I get them?

**Tuna Sandwich** and **Cheese Cake** cant be crafted. It doesn't look like it's intentional.

And these following ingredients don‘t have their characteristic recipes, I mean none of their recipes use their own tags so that could be substituted by other crops, it seems a little pointless to grow them:
```
Star Fruit
Plum
Persimmon
Pear
Nectarine
Grapefruit
Dragon Fruit
Turmeric
Honedew
Currant
Cauliflower
Cantaloupe
```
I think it's always good to have a characteristic recipe for each of these crops as well:)

Thanks for creating such a cute mod! Good luck!

**Comment by ExcessiveAmountsOfZombies** [comment] 2022-07-11 18:47
`The recipes of Buttered Green Beans and Melon Juice use wrong tags.` this has been fixed in some version after the issue, the rest is duplicate of #67, and giving the rest of the base foods recipes is something I'm working towards still.

**Closed by ExcessiveAmountsOfZombies** 2022-07-11 18:47 UTC
Labels: bug
