### ISSUE TITLE
banana cream pie recipe log entry error

### ISSUE THREAD

**Issue by Xigzagamer** [ExcessiveAmountsOfZombies/Croptopia#90] opened 2021-04-10 20:02 UTC
**Version**
Croptopia-1.16.4-5-FABRIC-1.3.3

**Platform**
(Fabric)

**Describe the issue**
There's an error in the banana cream pie recipe showing up in the logs.

**To Reproduce**
Load the game and look at the log entries.

**Log entry**
[14:35:43] [main/ERROR]: Parsing error loading recipe croptopia:banana_cream_pie

**Other Mods**
Adorn, bedspreads, better caves, better end, byg, cave biomes, chime, cosmetic armor, curios, custom player models, environmental armor, extra origins, fabric api, fabric language kotlin, go fish, lithium, mob origins, mod menu, mod menu, more drinks, okzoomer, origins, origins classes, pehkui, phosphor, respawnable pets, roughly enough items, save my stronghold, sodium, YungsApi

**Additional context**
I'm trying to debug a datapack I'm making for someone's server and this error is spamming the log entries by showing up every time I open a world.

**Comment by RDKRACZ** [comment] 2021-04-10 20:39
Duplicate of https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/67

**Comment by ExcessiveAmountsOfZombies** [comment] 2021-04-10 21:02
this will be fixed in 1.3.4

**Comment by ExcessiveAmountsOfZombies** [comment] 2021-05-02 16:31
This is fixed in 1.3.6, Thank you!

**Closed by ExcessiveAmountsOfZombies** 2021-05-02 16:31 UTC
Labels: future build
