### ISSUE TITLE
[1.21-Neo] Crash on boot.

### ISSUE THREAD

**Issue by Gbergz** [ExcessiveAmountsOfZombies/Croptopia#630] opened 2024-07-20 21:25 UTC
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

NeoForge

### Minecraft version.

1.21

### Croptopia version.

3.0.6

### What happened?

Booting the game crashes the client to desktop.

### Relevant logs

latest.log: https://gist.githubusercontent.com/Gbergz/49db5b226d2493b4429f303946ef4248/raw/ae606069d9921ae03350770db41a6fd9f58fd18c/gistfile1.txt

crash-report: https://gist.githubusercontent.com/Gbergz/ab7a19d520d0aeb21c1be896d9f26bc5/raw/4773449af0593d53df77f9cd289f0b0f37458d63/gistfile1.txt

### Additional information

thats it.

**Comment by Periam** [comment] 2024-07-20 22:33
I have the same issue

[crash-2024-07-20_19.30.38-fml.txt](https://github.com/user-attachments/files/16322515/crash-2024-07-20_19.30.38-fml.txt)


![image](https://github.com/user-attachments/assets/c38f295e-c23a-4015-9c5b-64ca4a42d204)

**Comment by FreedomsCupcake** [comment] 2024-07-21 01:42
I’m having this issue as well. Same error screen as above.

**Comment by siniel52** [comment] 2024-07-21 07:55
Just want to add - I have same :c

**Comment by SirTwsted** [comment] 2024-07-22 00:34
YUP,  I can confirm it.

![Screenshot_314](https://github.com/user-attachments/assets/40bf4507-af17-4e54-ba54-a20de9c75051)


![Screenshot_315](https://github.com/user-attachments/assets/c5da1251-9d08-41e3-b8cb-b9618e7c8708)


.

**Comment by Pomshi** [comment] 2024-07-23 01:23
I am having this issue as well, and also on Lunar Client 1.20.4 Fabric

**Comment by 2ndRecon** [comment] 2024-07-24 16:50
Same:

Attempted loading ONLY Croptopia + the required Lib with a fresh Neo-21.0.0 as well as 21.0.130 & 21.0.133 and received same error log.

**java.lang.IllegalStateException: Cannot register new entries to DeferredRegister after RegisterEvent has been fired.

at TRANSFORMER/croptopia@0.0NONE/com.epherical.croptopia.biome.SaltModifier.<clinit>(SaltModifier.java:26)

https://docs.neoforged.net/docs/concepts/registries/





![image](https://github.com/user-attachments/assets/5442a666-fcc2-4409-a5ff-e0803a81b794)







Update: Appears to work in Fabric 0.16.0; I don't know if that helps you or not. 

[11:59:04] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.16.0
[11:59:05] [main/INFO]: Loading 55 mods:
	- croptopia 3.0.6
	- epherolib 1.2.0-1.20.6
	- fabric-api 0.100.7+1.21

**Comment by Faye-Rhayne** [comment] 2024-07-25 15:32
I am having this issue as well, and I have tried it both by itself as a mod with EpheroLib and with the mods I was planning on using it with. It looks like the issue started about 5 days ago, when the versio updated to 3.0.6, but unfortunately there's no way to rollback to 3.0.5.

**Comment by Gbergz** [comment] 2024-07-28 10:30
Latest released version (v3.0.9) still crashes.

NeoForge: 21.0.139
Croptopia: 3.0.9

Crash-report:  https://gist.githubusercontent.com/Gbergz/a1c45bebac462bd6de766e83006f1251/raw/fa06876121b68fa16617ff138a767a71fbd9c288/gistfile1.txt

Latest.log: https://gist.githubusercontent.com/Gbergz/d31672b731ea77a6320a2c7d6fb28957/raw/cd7dc73128da91aa2cdc3c70022b653034b3aad9/gistfile1.txt

### EDIT: Seems like it needs [EpheroLib](https://www.curseforge.com/minecraft/mc-mods/epherolib) which it doesn't download automatically. 
### When downloading it manually the game now boots.

**Comment by MokahTGS** [comment] 2024-07-29 21:45
Confirmed that Croptopia has a dependency on [EpheroLib](https://www.curseforge.com/minecraft/mc-mods/epherolib) that isn't seen by the Curseforge Launcher.

**Comment by ExcessiveAmountsOfZombies** [comment] 2024-08-04 15:46
all fixed now! the main crash at least. just make sure to have epherolib installed for 3.0.9

**Closed as completed by ExcessiveAmountsOfZombies** 2024-08-04 15:46 UTC
