### ISSUE TITLE
Huge lag and ram usage sometimes when saplings grow into trees

### ISSUE THREAD

**Issue by VeggeieDude** [ExcessiveAmountsOfZombies/Croptopia#268] opened 2021-11-23 05:45 UTC
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.7.0

### What happened?

Whenever a sapling from croptopia grows into a tree, sometimes it will cause huge lag and I basically have to shut the server down

**Comment by ExcessiveAmountsOfZombies** [comment] 2021-11-23 17:49
There must be something else going on here because tree generation didn't change between 1.6.3 and 1.7.0.

**Comment by VeggeieDude** [comment] 2021-11-24 05:26
Well the only trees that do this are from Croptopia. It could be another mod interfering with it or something, not sure. Can't get a crash log either because the world doesn't crash, just gets locked and gotta shut the game down.

The only thing I could think of is the world gen datapack I'm using (strider's redux II) but even then none of the other trees do this

**Comment by VeggeieDude** [comment] 2021-11-24 06:30
I am gonna try it without the snowy mod too, the one that makes every biome cold and have snow. Maybe there's a problem with the two together, all I can think of besides the world gen datapack lol. I'll let you know if it fixes it or not, thank you for the quick response!

**Comment by SalvieMundi** [comment] 2021-12-26 12:17
Can confirm I am experiencing the same issues. Been poking around the code, and can only think that it must be some sort of mod incompatibility. Can't confirm if letting the saplings grow naturally causes this, but bonemealing absolutely does, more often than not. But not every time.

**Comment by SalvieMundi** [comment] 2021-12-26 15:21
Also of note, this issue occurred for me on 1.6.2, so I kept upgrading until I am now on a freshly compiled version of 1.7.2 for 1.17.1, and it occurs on every version I tested. So something definitely seems to be happening on Croptopia's end, but no clue as to whether the actual fix will be with this mod or whatever else might be causing problems. Worth noting, I have other mods like Traverse and Better End that add many other types of trees, and the only trees causing this issue are the Croptopia ones. But after a lot of code scrolling, I don't see any significant difference with how you manage your trees versus Traverse.

**Comment by SalvieMundi** [comment] 2021-12-26 16:15
Sorry to blow you up on this, but it's rather game breaking for anyone wanting to grow a lot of these crops in survival, and I'm trying to figure out what's going on and potentially send you a PR xD

Cinnamon trees no longer exhibit this behavior, after me switching line 343 of GeneratorRegistry to a SimpleBlockStateProvider for the leaves (no need for the WeightedBlockStateProvider there, since there's only one kind of leaf). Which leads me to believe this has something to do with the fact that Cinnamon trees use the SimpleBlockStateProvider for leaves while I've left all other trees with the WeightedBlockStateProvider. Will do more testing to confirm.

**Comment by ExcessiveAmountsOfZombies** [comment] 2021-12-26 20:26
I've gone through to try and replicate this again and I just can't seem to do it.

I've tried planting a ton of croptopia trees on top of a mountain and a ton of vanilla trees on top of the same mountain, afterwards the croptopia tree world had about ~100MB higher peaks looking at F3.

After closing the worlds and the game, and then going back into the worlds, without doing anything, it seems that the one planted with croptopia trees had a higher usage as well. which isn't even helpful because if I load into the world and do nothing, where is the extra RAM usage coming from?

Maybe what you are seeing is you're already near your RAM allocation and the croptopia tree is just enough to put it at 100%? I'm not sure.

Some questions:
What distribution of java do you use? (might have an effect?)
How many trees are we talking about planting (I planted probably around 75)
Is your ram usage already near max capacity when planting your trees?

When I originally tested this I ran the vanilla server and planted a bunch of trees and never saw the graph create spikes when I bonemeal grew them.

**Comment by SalvieMundi** [comment] 2021-12-26 21:07
Here is all I've I've found out:

Platform: Fabric
Minecraft: 1.17.1
Croptopia Versions: 1.6.2 - 1.7.2
Java Version: 17 LTS

Bug is almost certainly a bad mod interaction, as it is not reproducible on a server which only has this mod installed.

Bug is very specifically in regards to Croptopia trees growing from saplings, and does not seem to affect the Cinnamon tree at all, after doing more testing, both before and after my code modification mentioned above. This issue does not occur with any other trees, whether vanilla or modded.

To reproduce, I plant a Croptopia sapling and bonemeal until it is supposed to grow. Once it is supposed to grow, there are 3 possible outcomes:

1. Server immediately hangs and is unresponsive to all console commands. Sapling never disappears, tree does not grow. On client, I can no longer place blocks, mob ai ceases to function, etc. The server goes into an endless tick which eventually "crashes" the server by triggering Minecraft's built-in server tick check, whereby Minecraft Server jar terminates itself when the time between two ticks is greater than a certain number of seconds. This is the most likely outcome.

2. Sapling disappears and tree begins to form. Usually just one wooden block forms, but for sure, the leaves never start to form. At this point, server hangs and is identical to behavior described above in 1.

3. Tree grows as normal. No RAM spikes or server hangs. This is exceptionally rare.

The very specific behavior seems to indicate a variety of things:

1. Bad mod interaction -- the server does not hang when I am not running 368 other mods.

2. There is *some* difference between how you are either creating or registering your saplings, generators or leaves compared to other mods that creates the issue specifically and only for Croptopia. Whatever the other mod is in this interaction is likely the true culprit,  but there is almost certainly something that can be done differently here to prevent the interaction as well, and I frankly don't have time to reboot and retest Croptopia with 368 other mods. 🤣 So this is the approach to fixing that I have been taking (forked your code and have been looking through it, comparing to other mods with unaffected saplings / trees like Outvoted, Traverse, Promenade, and Woods and Mires).

3. The server hang with no crash log and no errors would seem to indicate a bad for or while loop somewhere -- whether that would be something in this mod or whatever the other mod is causing this compatibility issue, I don't yet know. (On a side note, did you mean jsonElement on [line 77](https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/fabric/src/main/java/me/thonk/croptopia/loottables/BiomeLootCondition.java) instead of just json? This is not a potential fix, already tried it and see no real difference regardless of which variable I use, but the way it's in that for loop seems to indicate jsonElement should be there rather than just json).

4. Whatever is causing this, doesn't seem to mind generating the trees during chunk generation, only when bonemealing a sapling.

**Comment by SalvieMundi** [comment] 2021-12-26 21:12
Also, to answer your only unanswered question, my RAM usage is only about half utilized until the server hang occurs. Then it shoots up to near 100% and stays there until the Minecraft Server jar unceremoniously kills itself after a tick takes more than 60 seconds.

**Comment by ExcessiveAmountsOfZombies** [comment] 2021-12-26 21:23
yea that jsonElement bit is most likely a bug.

Ok, that's some good info. if it's happening not on chunk generation and only on sapling bonemealing. I would guess that there could be a mod that is using mixins in SaplingBlock, or possibly the abstract SaplingGenerator class

maybe try adding `-Dmixin.debug=true` as a startup property and check the log file/send it here. I would expect to see a SaplingBlock or SaplingGenerator mixin.

**Comment by SalvieMundi** [comment] 2021-12-26 21:48
Will do, give me an hour or so, got other projects I'm in the middle of. ☺️

**Comment by SalvieMundi** [comment] 2021-12-26 22:16
It's kind of insane how many of these mods don't pass the mixin debug. That said, I have yet to see anything sapling related with any of the mixins.. We may be at an impass, a version of LibCD is failing and it could be any version packaged in a LOT of these mods.

I do see a BoneMealMixin class in Croptosis, might go look at what's going on there.

Here's the log before the LibCD crash.
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/7777646/latest.log)

**Comment by SalvieMundi** [comment] 2021-12-26 22:58
I've started just removing chunks of mods to rule out. I really didn't want to do this, but at this point, it's probably going to be the quickest (albeit most painful) way, unfortunately...

 It's not Apple Trees Revived, BC Lib, Better End, Krypton, Immersive Portals, Repurposed Structures, The Graveyard, Croptosis or Waystones. Which realistically leaves these:

	- additionaladditions@2.2.0
	- adorn@2.2.0+1.17.1
	- adventurez@1.4.3
	- alaskanativecraft@1.3.1
	- amecs@1.3.4+mc.1.17
	- amecsapi@1.1.5+mc21w16a
	- animal_feeding_trough@1.0.2
	- annotateddi@2.0.3+1.17.1
	- antiqueatlas@6.1.1-fabric-mc1.17.1
	- aopalliance_aopalliance@1.0
	- aqupdcaracal@1.17-1.3.2
	- aqupdgrizzly@1.17-1.2.0
	- architectury@2.6.35
	- artifacts@5.0.2+fabric
	- autosmeltenchant@1.1.0
	- awesomedungeon@1.1.2
	- backslot@1.2.2
	- backslotaddon@1.0.7
	- basicshields@1.1.1-1.17.1
	- battletowers@3.4.1-1.17.1
	- beaconoverhaul@1.4.2+1.17
	- beebuddy@1.1.3+1.17.1
	- bendy-lib@2.0.4
	- better_withered_mobs@1.6.1
	- betterdungeons@1.17-1.0.2
	- bettermineshafts@1.17-1.0.1
	- betterstrongholds@1.17-1.1.2
	- bitsofbark@0.1
	- blackstonetools@2.0.0+1.17
	- blockus@2.2.10+1.17.1
	- boatcontainer@1.0.3
	- bookworm@1.0.0
	- bosses_of_mass_destruction@1.3.2-1.17.1
	- bountiful@1.0.0
	- brewable_experience@1.1.1
	- caelus@0.0.18-1.17.1
	- capybara@1.0.0
	- castle_dungeons@3.0-1.17-fabric
	- cavebiomeapi@1.2.2
	- chalk@1.0.2
	- cloth-api@2.0.54
	- cloth-basic-math@0.6.0
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.1.40
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- collective-fabric@3.9
	- columns@1.2.0
	- com_electronwill_night-config_core@3.6.4
	- com_electronwill_night-config_toml@3.6.4
	- com_eliotlash_mclib_mclib@18
	- com_eliotlash_molang_molang@18
	- com_google_inject_guice@5.0.1
	- com_typesafe_config@1.4.1
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- comforts@0.0.7-1.17.1
	- completeconfig@1.1.0
	- confabricate@2.2.0-SNAPSHOT+4.1.1
	- consistency_plus@0.4.1-rc.3+1.17
	- cr-arrows-info@1.1.0+1.17
	- craftablechainmail@1.0.0
	- croptopia@1.7.2
	- customizableelytra@1.5.1-1.17
	- darkpaintings@4.0.2
	- dawn@2.0.6
	- dehydration@1.2.5
	- desolation@1.2.0
	- disenchanter@0.1.2
	- dragondropselytra-fabric@1.4
	- dragonloot@1.0.9
	- dualwielding@1.0.6
	- dungeons_arise@2.1.49-fabric
	- earthtojavamobs@1.7.3+1.17
	- editsign@2.2.4
	- emotecraft@2.1-SNAPSHOT-build.8
	- enchant_giver@1.1.0
	- endgoblintraders@1.3.0
	- endrem@4.1.0
	- environmentz@1.1.7
	- expandability@4.0.2
	- explorerscompass@1.17.1-2.0.2-fabric
	- extra_enchants@0.1.4
	- fabricshieldlib@1.4.5+1.17
	- fading@1.3.0
	- fastfurnace@1.17-3.0
	- ferritecore@3.1.0
	- fiber@0.23.0-2
	- fireplacelib@6.0.7+1.17.1
	- flonters@1.2.1+1.17.1
	- geckolib3@3.0.29
	- geodes@1.0.4
	- glassdoor@1.5.0-1.16
	- go-fish@1.3.1-1.17.1
	- gobber2@2.4.60
	- goblintraders@1.3.0
	- goprone@1.0
	- guardiansgalore@1.17.1-2.1
	- guild@0.3.4
	- harvest_scythes@2.1.0
	- hookshot@22.0
	- icarus@1.3
	- io_leangen_geantyref_geantyref@1.3.11
	- jankson@3.0.1+j1.2.0
	- java@17
	- javax_inject_javax_inject@1
	- just_end_anchor@1.0.1
	- kambrik@1.1.0
	- koi@1.0.1
	- lakeside@1.1.0+1.17
	- lazydfu@0.1.2
	- libcd@3.0.3+1.16.3
	- libgui@4.2.1+1.17.1
	- libninepatch@1.1.0
	- lithium@0.7.5
	- lovely_snails@1.0.3+1.17
	- maelstrom_library@1.2.2-1.17.1
	- magiccombatwands@1.0.1
	- mavm@1.0.5
	- maybe-data@1.0.1-1.17
	- mcda@1.7.15
	- mcdar@1.4.2
	- mcdw@3.6.0
	- mcsa@2.3.2-1.17
	- minecraft@1.17.1
	- mm@2.3
	- mo_glass@1.5-MC1.17.1
	- morebannerfeatures@1.1.1
	- moreflowerpots@2.0-SNAPSHOT
	- morevillagers-fabric@2.1.1-SNAPSHOT
	- mostructures@1.3.0-pre1-1.17.1
	- multipart_entities@1.1.3-1.17.1
	- musketmod@1.4.1
	- mythic-mounts@1.17.1-3.0
	- naturescompass@1.17.1-2.0.1-fabric
	- nears@1.1.2
	- netherroof@1.0.2
	- no_null_processors@1.0.0+1.17.1
	- notforgotten@1.0.1
	- npcvariety@2.2.0
	- nyfsquivers@0.2.6
	- omega-config@1.0.8
	- openloader@3.0.1
	- outvoted@2.0.14
	- outvoted_new@1.5.0
	- owo@0.3.2+1.17
	- paradoxconfig@0.5.1-beta
	- patchouli@1.17.1-59-FABRIC
	- patternedglass@1.17-1.0.1
	- pettable@1.2.0
	- physicsmod@2.5.17
	- pigsteel@1.6.6
	- pitch-dark@2.0.0
	- plushies@1.1
	- polymorph@0.0.14-1.17.1
	- promenade@2.1.2
	- pugh_lib@1.1.6
	- pugh_tools@1.0.5
	- q_misc_util@0.34
	- randore@1.3.1
	- ratsmischief@1.3.2
	- reach-entity-attributes@2.1.1
	- reinfbarrel@1.0.4+1.17
	- reinfchest@1.0.4+1.17
	- reinfcore@1.1.1+1.17
	- reroll@1.3.0-1.17.1
	- ripplers@0.3.1
	- riverredux@0.2.0
	- roughlyenoughitems@6.2.351
	- secondchance@1.2.0
	- sheepconsistency@1.0.3
	- shulkerutils@1.0.4-1.17
	- shwfox@1.1+fabric
	- simple_backpack@1.1.19
	- skeletonhorsespawn-fabric@1.9
	- slimyfloor@1.17.1-1.2.0
	- smoothboot@1.16.5-1.6.0
	- snowpig@1.0.0
	- snowundertrees@1.0.0
	- solidxp@1.0.0
	- somnus@0.0.13-1.17.1
	- starlight@1.0.0+fabric.73f6d37
	- starterkit-fabric@2.6
	- static-content@1.0.2-1.16.2
	- staticdata@1.1.2
	- step-height-entity-attribute@1.0.0
	- stonecutter_recipe_tags@1.1.0
	- stoneholm@1.3
	- stonevaults@1.1.0
	- strawgolem@1.10-B5
	- structure-helpers@3.2.0
	- terraform-biome-builder-api-v1@2.0.0
	- terraform-config-api-v1@2.0.0
	- terraform-overworld-biome-extensions-api-v1@2.0.0
	- terraform-shapes-api-v1@1.0.4
	- terraform-surfaces-api-v1@2.0.0
	- terraform-tree-api-v1@2.0.0
	- terraform-wood-api-v1@2.0.2
	- terrarianslimes@1.1-BETA+1.17
	- things@0.2.7
	- thonkutil@1.2
	- transliterationlib@1.2.2
	- transportables@1.0.6
	- traverse@4.0.0
	- trinkets@3.0.4
	- unlimiteddragoneggs@1.2.1
	- untitledduckmod@0.3.0
	- upgradedshulkers@1.1.1-1.17
	- urns@1.0.1
	- vanilla_degus@1.2.4
	- vanillaplusbiomes@0.3.2
	- villagernames@2.0.1
	- voicechat@1.17.1-2.1.28
	- vorpal-enchantment@1.0.0
	- windchimes@1.2.0
	- wolveswitharmor@1.6.1-1.17.1
	- woods_and_mires@1.1.1+1.17
	- wthit@3.11.2
	- yungsapi@1.17-Fabric-19
	- zombiehorsespawn-fabric@3.0

I'll let you know when I finally strike gold lol....

**Comment by ExcessiveAmountsOfZombies** [comment] 2021-12-26 23:02
damn, yea, that's a lot of mods

**Comment by SalvieMundi** [comment] 2021-12-27 20:30
It's Straw Golem. Most likely [this mixin](https://github.com/t2pellet/strawgolem/blob/master/src/main/java/com/commodorethrawn/strawgolem/mixin/GrowthMixin.java), lines 23 - 29.

**Comment by ExcessiveAmountsOfZombies** [comment] 2021-12-27 20:38
yup, dang that's fast

**Comment by SalvieMundi** [comment] 2021-12-27 20:43
only took me going through the majority of the mods first. xD

**Comment by ExcessiveAmountsOfZombies** [comment] 2021-12-27 20:56
looks like that chain of methods would be the culprit

![image](https://user-images.githubusercontent.com/30448663/147506559-794d3f80-0ec0-4a42-a6bc-9fd270933638.png)

**Comment by SalvieMundi** [comment] 2021-12-27 21:00
Gonna try adding the Croptopia "tree crops" to their blacklist and see if that works. If not I'll probably try and fork their code and send them a PR.

**Comment by SalvieMundi** [comment] 2021-12-27 21:07
Putting the following into their config's blacklist works as a stopgap solution, but there is probably a better one in code that would prevent users from needing to modify Straw Golem config out of the box. Would assume this is something they will need to fix.

blacklist = [croptopia:apple_crop,croptopia:banana_crop,croptopia:orange_crop,croptopia:persimmon_crop,croptopia:plum_crop,croptopia:cherry_crop,croptopia:lemon_crop,croptopia:grapefruit_crop,croptopia:kumquat_crop,croptopia:peach_crop,croptopia:coconut_crop,croptopia:nutmeg_crop,croptopia:fig_crop,croptopia:nectarine_crop,croptopia:mango_crop,croptopia:dragonfruit_crop,croptopia:starfruit_crop,croptopia:avocado_crop,croptopia:apricot_crop,croptopia:pear_crop,croptopia:lime_crop,croptopia:date_crop,croptopia:almond_crop,croptopia:cashew_crop,croptopia:pecan_crop,croptopia:walnut_crop]

**Comment by Neuans** [comment] 2021-12-28 05:15
luckily i managed to find this problem here. I had the same issue... I had to disable the Mod Straw Golem to solve the problem. Unfortunately... i hope soon we could have a fix to this :/

**Closed** 2022-03-21 20:39 UTC
Labels: bug
