### ISSUE TITLE
Crops don't spawn with Terralith 

### ISSUE THREAD

**Issue by euquinox** [ExcessiveAmountsOfZombies/Croptopia#590] opened 2024-01-21 12:00 UTC
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

3.0.4

### What happened?

Crops don't spawn even in vanilla biomes with Terralith present. Trees do spawn, but only in vanilla biomes.
And not too long ago the game used to crash on startup with only Terralith and Croptopia, but I think that was because I was using an older version of the Forge loader. Now it doesn't crash but the crops simply won't spawn.
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/14001106/latest.log)

### Additional information.

Mods:

Rubidium
Oculus
Terralith
Croptopia
Terrablender
Regions Unexplored

**Comment by zagdrath** [comment] 2024-01-21 14:54
Currently having the same exact issue.

**Comment by icezyclon** [comment] 2024-02-18 20:18
Agreed, we have the same issue on our server (Trees work fine)

Versions:
Minecraft: 1.20.4
Forge: 49.0.26
Croptopia: 3.0.4
Terralith: 2.4.11

**Comment by Polarstarzz** [comment] 2024-02-20 15:11
Having the same problem.

**Comment by Mikemece** [comment] 2024-02-24 22:54
Same problem, trees working fine but no crops spawning

Versions:
Minecraft: 1.20.1
Forge: 47.1.96
Croptopia: 3.0.4
Terralith: 2.4.11

**Comment by ashley-holton** [comment] 2024-05-09 18:05
Also having the same issue. We can find crops on trees, but not in the wild growing from the ground.

Versions:
Minecraft: 1.20.1
Croptopia: Croptopia-1.20.1-FORGE-3.0.4
Terralith: Terralith_1.20.4_v2.4.11

**Comment by leterio** [comment] 2024-07-26 16:06
Same issue here.

For my world, I've made a workaround datapack, changing the loot table of grass and tall grass to include the seeds from croptopia (and beetroot for convenience).

[croptopia-seeds-from-grass.zip](https://github.com/user-attachments/files/16394038/croptopia-seeds-from-grass.zip)

Versions:
Minecraft: 1.20.1
Forge: 47.2.5
Croptopia: 3.0.4
Terralith: 2.5.4
and others

**Comment by Hazzzzzzzzzzzzzzzzzx** [comment] 2024-07-27 11:46
> Versions: Minecraft: 1.20.1 Forge: 47.
Does that work with fabric 1.21?

**Comment by xWantex** [comment] 2024-08-17 03:51
Also happening in 1.21

**Comment by ExcessiveAmountsOfZombies** [comment] 2024-11-03 21:36
fixed in 4.0.0

**Closed as completed by ExcessiveAmountsOfZombies** 2024-11-03 21:36 UTC
Labels: bug

**Comment by mmnvb** [comment] 2024-11-08 07:08
Please make 4.0.0 version for 1.20.1 as well

**Comment by mmnvb** [comment] 2024-11-09 04:52
> fixed in 4.0.0

Hi. Can you briefly describe the bug source. I would try to fork and fix that for 1.20.1

**Comment by LocusAzzurro** [comment] 2025-02-28 16:33
> > fixed in 4.0.0
> 
> Hi. Can you briefly describe the bug source. I would try to fork and fix that for 1.20.1

After 2 days of trial and error I think I found a workaround consisting of using `minecraft:block_column` feature to circumnavigate the problem with `canSurvive` checks which I suspect to be the cause. Thought I'd post it here if anyone is in need.

First, the configured feature
```
{
  "type": "minecraft:random_patch",
  "config": {
    "tries": 4,
    "xz_spread": 4,
    "y_spread": 4,
    "feature": {
      "feature": {
        "config": {
          "direction": "up",
          "allowed_placement": {
            "type": "minecraft:true"
          },
          "prioritize_tip": false,
          "layers": [
            {
              "height": 1,
              "provider": {
                "type": "minecraft:weighted_state_provider",
                "entries": [ // put desired crop blocks here ]
        },
        "type": "minecraft:block_column"
      },
      "placement": [
        {
          "type": "minecraft:block_predicate_filter",
          "predicate": {
            "type": "minecraft:matching_blocks",
            "blocks": "minecraft:air"
          }
        },
        {
          "type": "minecraft:block_predicate_filter",
          "predicate": {
            "type": "minecraft:matching_blocks",
            "offset": [
              0,
              -1,
              0
            ],
            "blocks": "minecraft:grass_block"
          }
        }
      ]
    }
  }
}
```

Then a placed feature:
```
{
  "feature": "<the configured feature>",
  "placement": [
    {
      "type": "minecraft:count",
      "count": 4
    },
    {
      "type": "minecraft:in_square"
    },
    {
      "type": "minecraft:heightmap",
      "heightmap": "WORLD_SURFACE_WG"
    }
  ]
}
```
Using the `biome` modifier here caused some issue so I opted to remove it, so sometimes the crops go over biome boundaries.

Finally I used a `forge:add_features` biome modifier to add the feature in worldgen:
```
{
    "type": "forge:add_features",
    "biomes": "<desired biomes>",
    "features": "<the placed feature>",
    "step": "vegetal_decoration"
}
```

**Comment by Rokkano** [comment] 2025-02-28 20:09
Can this fix be realisticaly applied to a soon(ish) version or is it better to consider it as a hotfix ?

**Comment by mmnvb** [comment] 2025-03-15 00:47
@LocusAzzurro thank you!
