### ISSUE TITLE
Cannot craft salt

### ISSUE THREAD

**Issue by nicetiger** [ExcessiveAmountsOfZombies/Croptopia#515] opened 2023-03-18 21:57 UTC
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.2.2

### What happened?

I cannot craft salt. Neither in the furnace nor in the smoker.

### Additional information.

additional I have Create Mods Version 0.5.0.i

**Comment by nicetiger** [comment] 2023-03-19 20:13
I just found out that croptopia has introduced its own water bottle. With the croptopia water bottle, I was able to craft salt with the smoker. Why was there another water bottle introduced? It should also work with the vanilla water bottle.

**Comment by Ayutac** [comment] 2023-03-19 20:15
probably because it is stackable

**Comment by ExcessiveAmountsOfZombies** [comment] 2023-03-20 01:30
vanilla water bottles are just potions with nothing on them. I've just now thought of a possible way to use them as a water bottle but I'm going to close this as intended for now.

**Closed as completed by ExcessiveAmountsOfZombies** 2023-03-20 01:30 UTC
Labels: bug
